# NixOS configuration — Plasma 6 desktop with gaming setup
# (Intel CPU + AMD GPU, 8GB RAM, zram swap)
#
# NOTE: Replace placeholder values (marked with <...>) before using:
#   - networking.hostName
#   - time.timeZone
#   - users.users.<username>
#   - ./assets/wallpaper.png (bring your own wallpaper file)
#
# You'll also need a matching ./hardware-configuration.nix, which is
# machine-specific and generated by the NixOS installer — it is NOT
# included here and should not be shared publicly if it contains
# disk UUIDs/labels specific to your system (generally low-risk, but
# some prefer to keep it private).

{ config, lib, pkgs, ... }:

let
  sddmTheme = pkgs.stdenv.mkDerivation {
    name = "sddm-breeze-custom";
    dontUnpack = true;
    installPhase = ''
      mkdir -p $out/share/sddm/themes/breeze-custom
      cp -r ${pkgs.kdePackages.plasma-desktop}/share/sddm/themes/breeze/. \
        $out/share/sddm/themes/breeze-custom/
      cp ${./assets/wallpaper.png} \
        $out/share/sddm/themes/breeze-custom/background.png
      sed -i 's|^background=.*|background=background.png|' \
        $out/share/sddm/themes/breeze-custom/theme.conf || \
      echo "background=background.png" >> \
        $out/share/sddm/themes/breeze-custom/theme.conf
    '';
  };

  discordWrapped = pkgs.symlinkJoin {
    name = "discord";
    paths = [ pkgs.discord ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      wrapProgram $out/bin/discord \
        --add-flags "--js-flags=--max-old-space-size=384"
    '';
  };
in
{
  imports = [
    ./hardware-configuration.nix
  ];

  # ---------------------------------------------------------------------
  # Core system
  # ---------------------------------------------------------------------
  nixpkgs.config.allowUnfree = true;

  networking.hostName = "<your-hostname>";
  networking.networkmanager.enable = true;

  # LocalSend (LAN file transfer) — adjust/remove if unused
  networking.firewall.allowedTCPPorts = [ 53317 ];
  networking.firewall.allowedUDPPorts = [ 53317 ];

  time.timeZone = "<Region/City>"; # e.g. "Europe/Berlin"

  security.sudo.wheelNeedsPassword = true;

  users.users."<your-username>" = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "render"
    ];
  };

  # NOTE: stateVersion should match the NixOS release you FIRST installed
  # with — do not bump this when you upgrade channels.
  system.stateVersion = "26.05";

  # ---------------------------------------------------------------------
  # Boot
  # ---------------------------------------------------------------------
  boot.loader.grub.enable = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.configurationLimit = 2;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.tmp.cleanOnBoot = true;

  # High swappiness is intentional here: swap is zram (RAM-backed, compressed),
  # not disk, so aggressive swapping doesn't cause the usual disk-thrashing
  # slowdown. This is a common tuning choice for 8GB systems.
  boot.kernel.sysctl = {
    "vm.swappiness" = 60;
    "vm.vfs_cache_pressure" = 50;
  };

  # zram swap tuned for 8GB systems: keep swap fast (RAM-backed, compressed)
  # so high swappiness doesn't cause disk-style thrashing.
  # memoryPercent bumped 50 -> 60 for more headroom on a tight 8GB system.
  zramSwap = {
    enable = true;
    memoryPercent = 60;
    algorithm = "lz4";
  };

  # ---------------------------------------------------------------------
  # Desktop environment (Plasma 6 / SDDM)
  # ---------------------------------------------------------------------
  services.desktopManager.plasma6.enable = true;

  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    theme = "breeze-custom";
    extraPackages = [ sddmTheme ];
    settings.Theme.CursorTheme = "breeze_cursors";
  };

  qt.enable = true;
  qt.platformTheme = "kde";

  xdg.portal = {
    enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.kdePackages.xdg-desktop-portal-kde # Add this for Plasma 6 compatibility
    ];
    config.common.default = "*";
  };

  # NOTE on Baloo (KDE's file indexer): there's no NixOS module option
  # to disable it system-wide — it's a per-user Plasma setting. Disable
  # it with `balooctl6 disable` (or via System Settings > Search >
  # File Search) after rebuilding. It's a known background RAM/CPU
  # hog and worth turning off on this hardware.

  # ---------------------------------------------------------------------
  # System services
  # ---------------------------------------------------------------------
  services.power-profiles-daemon.enable = true;
  services.fstrim.enable = true;
  services.fwupd.enable = true;
  services.thermald.enable = true;
  services.flatpak.enable = true;
  services.journald.extraConfig = "SystemMaxUse=200M";

  services.pipewire = {
    enable = true;
    pulse.enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
  };
  services.pipewire.extraConfig.pipewire."99-low-power" = {
    "context.properties" = {
      "resample.quality" = 2;
    };
  };

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ---------------------------------------------------------------------
  # Graphics (Intel iGPU + AMD dGPU hybrid)
  # ---------------------------------------------------------------------
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-vaapi-driver
      libva-vdpau-driver
      libvdpau-va-gl
      mesa
      vulkan-loader
      vulkan-validation-layers
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      mesa
      vulkan-loader
    ];
  };

  hardware.cpu.intel.updateMicrocode = true;
  hardware.amdgpu.initrd.enable = true;
  hardware.enableRedistributableFirmware = true;

  # Hybrid graphics note: this config uses Mesa RADV (not AMDVLK) for the
  # AMD GPU, which is the lighter/recommended driver. To keep idle/desktop
  # work on the lighter Intel iGPU and reserve the AMD dGPU for games,
  # launch demanding apps with:
  #    DRI_PRIME=1 %command%
  # as a per-game Steam launch option, or `DRI_PRIME=1 <app>` from a terminal.

  # ---------------------------------------------------------------------
  # Gaming
  # ---------------------------------------------------------------------
  programs.steam = {
    enable = true;
    gamescopeSession.enable = true;
  };

  programs.gamescope = {
    enable = true;
    capSysNice = true;
  };

  programs.gamemode = {
    enable = true;
    enableRenice = true;
    settings = {
      general = {
        desiredgov = "none";
        renice = 10;
      };
      gpu = {
        apply_gpu_optimisations = "accept-responsibility";
        gpu_vendor = "amd";
        amd_performance_level = "auto";
      };
    };
  };

  # ---------------------------------------------------------------------
  # User programs
  # ---------------------------------------------------------------------
  programs.dconf.enable = true;
  programs.firefox.enable = true;

  programs.starship = {
    enable = true;
    settings = {
      add_newline = false;
      format = "$directory$git_branch$git_status$character";
      character = {
        success_symbol = "[➜](bold green)";
        error_symbol = "[➜](bold red)";
      };
    };
  };

  environment.systemPackages = with pkgs; [
    # CLI tools
    git
    wget
    curl
    tree
    unzip
    p7zip
    fastfetch

    # Terminal
    kitty

    # KDE / Plasma
    kdePackages.kate
    kdePackages.dolphin
    kdePackages.qtstyleplugin-kvantum
    kdePackages.plasma-systemmonitor
    kdePackages.sddm-kcm
    sddmTheme

    # Graphics / gaming utilities
    vulkan-tools
    mangohud
    prismlauncher

    # Audio
    pavucontrol

    # Apps
    localsend
    discordWrapped
    obsidian
  ];

  environment.etc."xdg/kitty/kitty.conf".text = ''
    cursor_shape block
    cursor_blink_interval 0
    cursor_trail 1
    cursor_trail_decay 0.1 0.4
  '';
}
