# NixOS configuration — Plasma 6 desktop with gaming setup
# (Intel CPU + AMD GPU, 8GB RAM, zram swap)
#
# Optimized for: Lenovo ideapad 330-15IKB, Intel Core i3-7020U
# (2C/4T, Kaby Lake), Intel HD 620 (iGPU) + AMD Radeon R5 M445 (dGPU), 8GB RAM
#
# Before using: replace `youruser` (username/home paths), `nixos-desktop`
# (hostName), and `time.timeZone` with your own values. Also requires a
# `./hardware-configuration.nix` (generated by the NixOS installer, not
# included here) and `./assets/wallhaven-ly395l_1920x1080.png` for the SDDM
# background, or you can swap that line out for your own wallpaper.

{ config, lib, pkgs, ... }:

let
  sddmTheme = pkgs.stdenv.mkDerivation {
    name = "sddm-breeze-custom";
    dontUnpack = true;
    installPhase = ''
      mkdir -p $out/share/sddm/themes/breeze-custom
      cp -r ${pkgs.kdePackages.plasma-desktop}/share/sddm/themes/breeze/. \
        $out/share/sddm/themes/breeze-custom/
      cp ${./assets/wallhaven-ly395l_1920x1080.png} \
        $out/share/sddm/themes/breeze-custom/background.png
      sed -i 's|^background=.*|background=background.png|' \
        $out/share/sddm/themes/breeze-custom/theme.conf || \
      echo "background=background.png" >> \
        $out/share/sddm/themes/breeze-custom/theme.conf
    '';
  };

in
{
  imports = [
    ./hardware-configuration.nix
  ];

  # ---------------------------------------------------------------------
  # Core system
  # ---------------------------------------------------------------------
  nixpkgs.config.allowUnfree = true;

  networking.hostName = "nixos-desktop";
  networking.networkmanager.enable = true;
  networking.firewall.allowedTCPPorts = [ 53317 ];
  networking.firewall.allowedUDPPorts = [ 53317 ];
  networking.nameservers = [ "1.1.1.1" "1.0.0.1" ];
  networking.networkmanager.dns = "none";

  time.timeZone = "Africa/Cairo"; # set this to your own timezone

  security.sudo.wheelNeedsPassword = true;

  users.users.youruser = {
    isNormalUser = true;
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "render"
    ];
  };

  # NOTE: stateVersion should match the NixOS release you FIRST installed
  # with — do not bump this when you upgrade channels.
  system.stateVersion = "26.05";

  # ---------------------------------------------------------------------
  # Nix store housekeeping
  # A weak CPU + small disk benefits more from these than most desktops
  # do: auto-optimise-store hardlinks identical files across derivations
  # (free disk space, ~zero runtime cost), and gc.automatic keeps old
  # generations from silently eating your drive.
  # ---------------------------------------------------------------------
  nix.settings.auto-optimise-store = true;
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 14d";
  };

  # ---------------------------------------------------------------------
  # Boot
  # ---------------------------------------------------------------------
  # linux_xanmod: preemptive, tickless scheduler tuned for desktop/gaming
  # responsiveness — the kernel the nix-gaming project defaults to.
  boot.kernelPackages = pkgs.linuxPackages_xanmod;

  boot.loader.grub.enable = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.configurationLimit = 2;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 1; # configurationLimit is already 2, so there's little
                            # reason to sit on the GRUB menu for 5s every boot
                            # on a spinning-rust-slow laptop.
  boot.tmp.cleanOnBoot = true;
  boot.kernelParams = [
    "amdgpu.runpm=1" # lets the dGPU power down between uses instead of
                      # staying spun up, since you only invoke it per-app
                      # via DRI_PRIME=1 rather than system-wide
  ];

  # High swappiness is intentional here: swap is zram (RAM-backed, compressed),
  # not disk, so aggressive swapping doesn't cause the usual disk-thrashing
  # slowdown. This is a common tuning choice for 8GB systems.
  boot.kernel.sysctl = {
    "vm.swappiness" = 100; # Kernel docs and the Arch wiki both note that for
                            # in-memory swap (zram/zswap) "values beyond 100
                            # can be considered" since the usual
                            # swap-is-slower-than-RAM penalty doesn't apply
                            # the same way — the kernel should feel free to
                            # swap out cold anonymous pages rather than evict
                            # useful file cache. 100 is the standard
                            # recommended starting point; nudge higher only
                            # if you've measured it helps.
    "vm.vfs_cache_pressure" = 50;
  };

  # zram swap tuned for 8GB systems: keep swap fast (RAM-backed, compressed)
  # so high swappiness doesn't cause disk-style thrashing.
  # memoryPercent bumped 50 -> 60 for more headroom on a tight 8GB system.
  #
  # lz4, not zstd: on a 2C/4T CPU that's also running a game, zstd's better
  # compression ratio isn't worth stealing cycles from the game loop during
  # swap activity. lz4 is roughly 2-3x faster to compress/decompress than
  # zstd at a lower ratio — the right trade on a CPU this weak. If you're
  # mostly swapping idle background junk (not under gaming load) and are
  # tighter on RAM than on CPU, zstd is a reasonable alternative.
  zramSwap = {
    enable = true;
    memoryPercent = 60;
    algorithm = "lz4";
  };

  # ---------------------------------------------------------------------
  # Desktop environment (Plasma 6 / SDDM)
  # ---------------------------------------------------------------------
  services.desktopManager.plasma6.enable = true;

  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    theme = "breeze-custom";
    extraPackages = [ sddmTheme ];
    settings.Theme.CursorTheme = "breeze_cursors";
  };

  qt.enable = true;
  qt.platformTheme = "kde";

  xdg.portal = {
    enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.kdePackages.xdg-desktop-portal-kde # Plasma 6 compatibility
    ];
    config.common.default = "*";
  };

  # Baloo (KDE's file indexer) auto-disabled at activation. Writes the config
  # KDE itself would write if you disabled indexing via System Settings, so
  # it's the same effect, just automated and reproducible across
  # rebuilds/reinstalls.
  system.activationScripts.disableBaloo = ''
    mkdir -p /home/youruser/.config
    if [ ! -f /home/youruser/.config/baloofilerc ]; then
      cat > /home/youruser/.config/baloofilerc <<'EOF'
[Basic Settings]
Indexing-Enabled=false
EOF
      chown youruser:users /home/youruser/.config/baloofilerc
    fi
  '';

  # ---------------------------------------------------------------------
  # System services
  # ---------------------------------------------------------------------
  services.power-profiles-daemon.enable = true;
  services.fstrim.enable = true;
  services.fwupd.enable = true;
  services.thermald.enable = true; # proactively throttles before hitting
                                    # critical temp instead of hard-crashing
  services.flatpak.enable = true;
  services.journald.extraConfig = ''
    SystemMaxUse=200M
    RuntimeMaxUse=50M
  '';
  services.pipewire = {
    enable = true;
    pulse.enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
  };
  services.pipewire.extraConfig.pipewire."99-low-power" = {
    "context.properties" = {
      "resample.quality" = 2;
    };
  };

  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ---------------------------------------------------------------------
  # Graphics (Intel iGPU + AMD dGPU hybrid)
  # ---------------------------------------------------------------------
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-vaapi-driver
      libva-vdpau-driver
      libvdpau-va-gl
      mesa
      vulkan-loader
      vulkan-validation-layers
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      mesa
      vulkan-loader
    ];
  };

  hardware.cpu.intel.updateMicrocode = true;
  hardware.amdgpu.initrd.enable = true;
  hardware.enableRedistributableFirmware = true;

  # With two GPUs present, libva can pick the wrong VAAPI backend for apps
  # doing hardware video decode on the Intel iGPU (Firefox, mpv, etc.),
  # silently falling back to software decode — which burns real CPU on this
  # chip. Your i3-7020U is Kaby Lake (Gen 9), so intel-media-driver ("iHD")
  # is the correct/modern driver, not the legacy i965 one. Pin it explicitly:
  environment.variables.LIBVA_DRIVER_NAME = "iHD";
  # Optional further trim: intel-vaapi-driver (legacy i965), libva-vdpau-driver,
  # and libvdpau-va-gl above are mostly dead weight on this hardware now that
  # iHD is pinned and Mesa RadeonSI already provides native VAAPI for the AMD
  # dGPU — you could drop all three from extraPackages to shrink the closure
  # a bit. Left in place here since they're harmless fallbacks, not a
  # correctness issue.

  # Hybrid graphics note: you have both an Intel iGPU and AMD dGPU.
  # This config already uses Mesa RADV (not AMDVLK) for the AMD GPU,
  # which is the lighter/recommended driver — no change needed there.
  # To keep idle/desktop work on the lighter Intel iGPU and reserve the
  # AMD dGPU for games, launch demanding apps with:
  #   DRI_PRIME=1 %command%
  # as a per-game Steam launch option, or `DRI_PRIME=1 <app>` from a terminal.

  # ---------------------------------------------------------------------
  # Gaming
  # ---------------------------------------------------------------------
  programs.steam = {
    enable = true;
    gamescopeSession.enable = true;
  };

  programs.gamescope = {
    enable = true;
    capSysNice = true;
  };

  programs.gamemode = {
    enable = true;
    enableRenice = true;
    settings = {
      general = {
        # "none" leaves the CPU governor alone entirely, since
        # power-profiles-daemon (enabled above) is already managing it
        # system-wide. Letting both GameMode and power-profiles-daemon try
        # to set the governor at once can cause them to fight/flap — this
        # keeps power-profiles-daemon as the single source of truth. Flip
        # to the Performance profile manually before gaming if you want:
        #   powerprofilesctl set performance
        desiredgov = "none";
        renice = 10;
      };
      gpu = {
        apply_gpu_optimisations = "accept-responsibility";
        gpu_vendor = "amd";
        # amd_performance_level left at "auto" — the safer choice on a
        # laptop dGPU with this little thermal headroom. "high" pins the
        # dGPU to max clocks for the whole gamemode session (lower input
        # latency, no ramp-up stutter) at the cost of more heat/battery
        # drain. Worth trying "high" if you find games GPU-bound and your
        # thermals have headroom; keep "auto" if you see throttling.
        amd_performance_level = "auto";
      };
    };
  };

  # ---------------------------------------------------------------------
  # User programs
  # ---------------------------------------------------------------------
  programs.dconf.enable = true;
  programs.firefox.enable = true;

  programs.starship = {
    enable = true;
    settings = {
      add_newline = false;
      format = "$directory$git_branch$git_status$character";
      character = {
        success_symbol = "[➜](bold green)";
        error_symbol = "[➜](bold red)";
      };
    };
  };

  environment.systemPackages = with pkgs; [
    # CLI tools
    git
    wget
    curl
    tree
    unzip
    p7zip
    fastfetch
    ncdu

    # Terminal
    kitty

    # KDE / Plasma
    kdePackages.kate
    kdePackages.dolphin
    kdePackages.qtstyleplugin-kvantum
    kdePackages.plasma-systemmonitor
    kdePackages.sddm-kcm
    sddmTheme

    # Graphics / gaming utilities
    vulkan-tools
    mangohud
    prismlauncher

    # Audio
    pavucontrol

    # Apps
    localsend
    vesktop
    obsidian
  ];

  environment.etc."xdg/kitty/kitty.conf".text = ''
    cursor_shape block
    cursor_blink_interval 0
    cursor_trail 1
    cursor_trail_decay 0.1 0.4
  '';
}
